language: objective-c
xcode_project: STHAL.xcodeproj
matrix:
    include:
        - xcode_sdk: iphonesimulator7.1
          xcode_scheme: STHAL-ios
        - xcode_sdk: iphonesimulator8.1
          xcode_scheme: STHAL-ios
        - xcode_sdk: macosx
          xcode_scheme: STHAL-mac
branches:
    only:
        - master
before_script:
    - brew update && brew upgrade xctool
